export {LoginPage} from './login'
export {RegistrationPage} from './registration'
export {ChatsPage} from './chats'
export {Page404} from './page404'
export {Page500} from './page500'
export {ProfilePage} from './profile'
export {StartPage} from './start'